# Generated by Django 3.2.7 on 2021-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
